name: Pulumi Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  pulumi-up:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./ppinfra
        run: npm install

      - name: Pulumi Up (with OIDC role)
        uses: pulumi/actions@v5
        with:
          command: up
          stack-name: siddharthpal18/myworkshop/Lab8
          work-dir: ./ppinfra
          config-map: |
            aws:assumeRoleArn=arn:aws:iam::285951302175:role/pulumi-role
            aws:region=us-east-1
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
