name: Pulumi Destroy

on:
  workflow_dispatch:  # Allows manual trigger

permissions:
  id-token: write
  contents: read

jobs:
  pulumi-destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: ./ppinfra
        run: npm install

      - name: Pulumi Destroy
        uses: pulumi/actions@v5
        with:
          command: destroy
          stack-name: siddharthpal18/myworkshop/Lab8
          work-dir: ./ppinfra
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}